const menu = [
  {
    id: 1,
    title: 'Ballı Pankek',
    category: 'kahvaltı',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Duble Izgara',
    category: 'akşam Yemeği',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Özel soslarla harmanlanmış,odun ateşinde pişmiş muhteşem bir 'duble' lezzet`,
  },
  {
    id: 3,
    title: 'Efsane Milkshake',
    category: 'içecekler',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Limon,çilek ve ahududunun sütle buluşması ile meydana çıkan lezzet.`,
  },
  {
    id: 4,
    title: 'Kır Kahvaltısı',
    category: 'kahvaltı',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Yumurtalı Nefis Burger',
    category: 'öğle yemeği',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'Oreolu Sütlü Karışım',
    category: 'içecekler',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Yumurtalı Sosisli Burger',
    category: 'kahvaltı',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Patates-Burger Menu',
    category: 'öğle yemeği',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Aşkla İçenler İçin',
    category: 'içecekler',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
